=== DaniPazLor/Asignaturas-1-DAM/LMSGI/Tarea 4/pedidos.dtd
<!ELEMENT pedidos  (sucursal+)>
<!ELEMENT sucursal (direccion+,codPedido,nomTrabajador,fechaPedido,observacion?,plazoRevision,articulo+)>
<!ATTLIST sucursal codSucursal CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA) >
<!ELEMENT codPedido (#PCDATA) >
<!ELEMENT nomTrabajador (#PCDATA) >
<!ELEMENT fechaPedido (#PCDATA) >
<!ELEMENT observacion (#PCDATA) >
<!ELEMENT plazoRevision (#PCDATA) >
<!ELEMENT articulo (unidadesPedidas,precio,observaciones?) >
<!ATTLIST articulo codArticulo CDATA #REQUIRED>
<!ELEMENT unidadesPedidas (#PCDATA) >
<!ELEMENT precio (#PCDATA) >
<!ELEMENT observaciones (#PCDATA) >

=== DaniPazLor/Asignaturas-1-DAM/LMSGI/Tarea 4/pedidosDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">
<?xml-stylesheet href="librohtml.xsl" type="text/xsl"?>

<pedidos>
    <sucursal codSucursal="12345678EF">
        <direccion>Calle de chopo numero 23</direccion>
        <codPedido>P5678azd</codPedido>
        <nomTrabajador>Juan Perez Gomez</nomTrabajador>
        <fechaPedido>2021-01-13</fechaPedido>
        <observacion>urgente</observacion>
        <plazoRevision>19</plazoRevision>
        <articulo codArticulo="FGB-378">
            <unidadesPedidas>58</unidadesPedidas>
            <precio>158,35</precio>
            <observaciones>Empaquetados en cajas de 4 packs</observaciones>
        </articulo>
    </sucursal>
        <sucursal codSucursal="65952AFA">
        <direccion>Calle Ferrari numero 78</direccion>
        <codPedido>Z687afgs</codPedido>
        <nomTrabajador>Paula Gomez Verde</nomTrabajador>
        <fechaPedido>2019-11-23</fechaPedido>
        <observacion>incompleto</observacion>
        <plazoRevision>5</plazoRevision>
        <articulo codArticulo="FGB-378">
            <unidadesPedidas>25</unidadesPedidas>
            <precio>310,85</precio>
            <observaciones>Transportar con sumo cuidado, muy frágil</observaciones>
        </articulo>
    </sucursal>
</pedidos>
