=== DaniPazLor/Asignaturas-1-DAM/LMSGI/Tarea 4/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Elementos -->
  <xs:element name="pedidos" type="tipoPedidos"/>
  
  <xs:element name="sucursal" type="sucursalDatos"/>
  
  <xs:element name="direccion" type="xs:string"/>
  <xs:element name="codPedido" type="tipoCodPedido"/>
  <xs:element name="nomTrabajador" type="xs:string"/>
  <xs:element name="fechaPedido" type="xs:date"/>
  <xs:element name="observacion" type="tipoObservaciones"/>
  <xs:element name="plazoRevision" type="xs:positiveInteger"/>
  <xs:element name="articulo" type="tipoArticulo"/>
  
  <xs:element name="unidadesPedidas" type="xs:positiveInteger"/>
  <xs:element name="precio" type="xs:decimal"/>
  <xs:element name="observaciones" type="xs:string"/>
  
  
  <!-- Atributos -->
  <xs:attribute name="codSucursal" type="xs:string"/>
  
  <xs:attribute name="codArticulo" type="tipoCodArticulo"/>


  <!-- Tipos de Datos (construidos y complejos) -->
  <xs:complexType name="tipoPedidos">
    <xs:sequence>
      <xs:element ref="sucursal" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sucursalDatos">
    <xs:sequence>
      <xs:element ref="direccion"/>
      <xs:element ref="codPedido" minOccurs="1" maxOccurs="1"/>
      <xs:element ref="nomTrabajador"/>
      <xs:element ref="fechaPedido"/>
      <xs:element ref="observacion"/>
      <xs:element ref="plazoRevision"/>
      <xs:element ref="articulo"/>
    </xs:sequence>
    <xs:attribute ref="codSucursal"/>
  </xs:complexType>

  <xs:simpleType name="tipoCodPedido">
    <xs:restriction base="xs:string">
      <xs:length value="8"/>
      <xs:pattern value="[A-Z a-z][A-Z a-z 0-9]{7}"/>
    </xs:restriction>
  </xs:simpleType>

<xs:simpleType name="tipoObservaciones">
    <xs:restriction base="xs:string">
      <xs:enumeration value="urgente"/>
      <xs:enumeration value="incompleto"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoArticulo">
    <xs:sequence>
      <xs:element ref="unidadesPedidas"/>
      <xs:element ref="precio"/>
      <xs:element ref="observaciones"/>
    </xs:sequence>
    <xs:attribute ref="codArticulo" use="required"/>
  </xs:complexType>
    
  <xs:simpleType name="tipoCodArticulo">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}[\-][0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== DaniPazLor/Asignaturas-1-DAM/LMSGI/Tarea 4/pedidosSCHEMA.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="librohtml.xsl" type="text/xsl"?>

<pedidos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="pedidos.xsd">
    <sucursal codSucursal="12345678EF">
        <direccion>Calle de chopo numero 23</direccion>
        <codPedido>P5678azd</codPedido>
        <nomTrabajador>Juan Perez Gomez</nomTrabajador>
        <fechaPedido>2021-01-13</fechaPedido>
        <observacion>urgente</observacion>
        <plazoRevision>19</plazoRevision>
        <articulo codArticulo="FGB-378">
            <unidadesPedidas>58</unidadesPedidas>
            <precio>158.35</precio>
            <observaciones>Empaquetados en cajas de 4 packs</observaciones>
        </articulo>
    </sucursal>
        <sucursal codSucursal="P5952AFA">
        <direccion>Calle Ferrari numero 78</direccion>
        <codPedido>Z687afgs</codPedido>
        <nomTrabajador>Paula Gomez Verde</nomTrabajador>
        <fechaPedido>2019-11-23</fechaPedido>
        <observacion>incompleto</observacion>
        <plazoRevision>5</plazoRevision>
        <articulo codArticulo="FGB-378">
            <unidadesPedidas>25</unidadesPedidas>
            <precio>310.85</precio>
            <observaciones>Transportar con sumo cuidado, muy frágil</observaciones>
        </articulo>
    </sucursal>
</pedidos>
